#!/usr/bin/env bash
# Case 7c: serve MDA's compiled app with ONE change to the generated graph
# factory, to show what MDA's runtime would need for distributed tracing.
#
# `mda dev` compiles mda_agent/ into .mda/build/ and runs `langgraph dev` there.
# This copies that build, wraps the factory in tracing_context like
# child_langgraph's `graph`, and serves it on :2026. Not a supported workaround:
# `mda deploy` regenerates _mda_entry.py ("Generated by `mda deploy` — do not edit").
set -euo pipefail
MDA="$(cd "$(dirname "$0")/../mda_agent" && pwd)"

if [ ! -f "$MDA/.mda/build/_mda_entry.py" ]; then
  (cd "$MDA" && uv run mda build >/dev/null)
fi
rm -rf "$MDA/.mda/patched"
cp -R "$MDA/.mda/build" "$MDA/.mda/patched"

python3 - "$MDA/.mda/patched/_mda_entry.py" <<'EOF'
import sys
from pathlib import Path

path = Path(sys.argv[1])
src = path.read_text()
old = "async def agent(config, runtime: ServerRuntime):\n    execution = runtime.execution_runtime\n    return await "
assert old in src, "MDA's generated factory changed shape; update this patch"
src = src.replace(old, (
    "@contextlib.asynccontextmanager\n"
    "async def agent(config, runtime: ServerRuntime):\n"
    "    execution = runtime.execution_runtime\n"
    "    configurable = config.get(\"configurable\", {})\n"
    "    graph = await "
))
src = src.rstrip("\n") + (
    "\n    # HARNESS PATCH: apply the caller's trace context, as the Agent Server docs describe.\n"
    "    with ls.tracing_context(\n"
    "        parent=configurable.get(\"langsmith-trace\"),\n"
    "        project_name=configurable.get(\"langsmith-project\"),\n"
    "        metadata=configurable.get(\"langsmith-metadata\"),\n"
    "        tags=configurable.get(\"langsmith-tags\"),\n"
    "    ):\n"
    "        yield graph\n"
)
src = src.replace("from managed_deepagents.runtime import", "import contextlib\n\nimport langsmith as ls\nfrom managed_deepagents.runtime import", 1)
path.write_text(src)
EOF

cd "$MDA/.mda/patched"
# Same local-only identity mode `mda dev` sets for its own server.
export MDA_LOCAL_DEV=1
exec uv run --with "langgraph-cli[inmem]>=0.4.30" langgraph dev --port 2026 --no-browser --no-reload
